### ISSUE TITLE
Large binary sizes

### ISSUE THREAD

**Issue by BigEpsilon** [image-rs/imageproc#242]
Hi,

I compiled the examples and I was surprised that each examples is approximately 16 M in size in release mode and 21M in debug mode.
After striping, I get 1.6M and 4.4M respectively  binary sizes.
That make the library practically unusable on constrained environments.
Is there a way to reduce the binaries sizes ? if no why ?

Thanks

**Comment by theotherphil** [comment]
I've no idea I'm afraid. Googling "Rust binary size" produces a lot of discussion about this, so the problem (and solution, if there is one) isn't specific to this library.

**Comment by philipc** [comment]
Note that this crate enables debuginfo in release mode, so you do need to strip that if you care about size. For the examples, the size of the code that comes from this crate is quite small (mostly less than 10k, but about 40k for the font example). So I don't think there's any problem with this crate.

Of the other crates, image (300k) and inflate (200k) are large contributors, so there may be saving possible there (eg disable image formats you don't need). The inflate size looks like poor optimization to me, it's all in one function (`inflate::InflateStream::next_state`).

There's also the base code from the std library. A sizable portion of this is due to jemalloc. This will be reduced once we can switch to using the system allocator.

**Comment by theotherphil** [comment]
I've just had a look at the gradients example. It's now 1.8mb in release mode, 1.1mb stripped. Cargo bloat output for the release build is shown below.

```
Analyzing target/release/examples/gradients

 File  .text     Size     Crate Name
 2.9%   5.8%  52.9KiB   inflate inflate::InflateStream::next_state
 1.7%   3.4%  30.9KiB     image image::webp::vp8::VP8Decoder<R>::decode_frame
 1.4%   2.7%  24.6KiB     image jpeg_decoder::decoder::Decoder<R>::decode_internal
 0.7%   1.3%  12.3KiB       png png::decoder::stream::StreamingDecoder::update
 0.7%   1.3%  12.0KiB     image image::dynimage::open_impl
 0.6%   1.1%  10.5KiB [Unknown] _read_line_info
 0.4%   0.9%   8.1KiB     image tiff::decoder::ifd::Entry::val
 0.4%   0.9%   7.9KiB     image tiff::decoder::Decoder<R>::read_image
 0.4%   0.9%   7.9KiB     image tiff::decoder::Decoder<R>::new
 0.4%   0.8%   7.4KiB       std ___rdos_backtrace_dwarf_add
 0.4%   0.8%   7.0KiB     image image::webp::vp8::predict_4x4
 0.4%   0.7%   6.4KiB     image image::tga::decoder::Header::from_reader
 0.3%   0.7%   6.2KiB     image image::hdr::decoder::HDRMetadata::update_header_info
 0.3%   0.6%   5.5KiB       gif gif::reader::decoder::StreamingDecoder::update
 0.3%   0.6%   5.5KiB     image image::bmp::decoder::BMPDecoder<R>::read_metadata
 0.3%   0.6%   5.1KiB     image image::pnm::decoder::HeaderReader::read_arbitrary_header
 0.3%   0.5%   4.9KiB     image jpeg_decoder::parser::parse_sos
 0.3%   0.5%   4.9KiB       std rustc_demangle::demangle
 0.3%   0.5%   4.9KiB       std <rustc_demangle::legacy::Demangle as core::fmt::Display>::fmt
 0.3%   0.5%   4.8KiB [Unknown] _read_attribute
38.0%  75.0% 689.3KiB           And 2508 smaller methods. Use -n N to show more.
50.7% 100.0% 919.0KiB           .text section size, the file size is 1.8MiB
```

**Comment by theotherphil** [comment]
Binary sizes with the settings shown above are now 10x smaller than those in the original report. If this is still too large then try the guide linked from the previous comment which explains how to build a smaller std.
