### ISSUE TITLE
`draw_filled_circle_mut` gives an ugly circle when radius is small

### ISSUE THREAD

**Issue by Aloxaf** [image-rs/imageproc#328]
This happens in when I try to draw a circle with small radius.

## Expected

(draw by pillow)
![circle_py](https://user-images.githubusercontent.com/17017672/60680311-598e0d00-9ebd-11e9-98ba-79e120598b9e.png)

## Actual behaviour

![circle](https://user-images.githubusercontent.com/17017672/60680446-f2248d00-9ebd-11e9-9ca8-bfa778594518.png)

(a more intuitive picture)
![图片](https://user-images.githubusercontent.com/17017672/60680503-29933980-9ebe-11e9-9a50-f2cd4ac9f114.png)

## Reproduction steps

```rust
let mut circle = DynamicImage::new_luma8(21, 21);

draw_filled_circle_mut(
    &mut circle,
    (10, 10),
    10,
    Rgba([255, 255, 255, 255]),
);
circle.save(std::path::Path::new("circle.png"));
```

```python
circle = Image.new('L', (21, 21), 0)
draw = ImageDraw.Draw(circle)
draw.ellipse((0, 0, 20, 20), fill=255)
circle.save('circle_py.png')
```

**Comment by fintelia** [comment]
Does it look right with a large radius? The code for the draw_filled_circle_mut function is [here](https://docs.rs/imageproc/0.15.0/src/imageproc/drawing/conics.rs.html#224-268). I'm not familiar with these sort of rasterization algorithms, but comparing to pillow the bug will be clear?

**Comment by theotherphil** [comment]
If you comment out the call to `draw_filled_circle_mut` in https://github.com/image-rs/imageproc/blob/master/src/drawing/conics.rs#L92 then `draw_filled_ellipse_mut` produces a result that looks to be correct. So the easiest fix looks to be just making the circle drawing functions forward to the ellipse drawing functions.

**Comment by Aloxaf** [comment]
@fintelia it works well with a large radius.  
There may be a problem of precision.

**Comment by HeroicKatora** [comment]
@theotherphil No, the opposite is already done :) https://docs.rs/imageproc/0.15.0/src/imageproc/drawing/conics.rs.html#103

The algorithm alone is probably correct (although not the most efficient?). Floating point error would be weird, inputs to line drawing are cast from integers so there is no build-up of precision lost. But it could be that that particular pixel is on a Pythagorean distance from the mid point, i.e. the distance is integer and the floating point rounds fails by rounding down?

**Comment by theotherphil** [comment]
@HeroicKatora yes, I removed that direction: https://github.com/image-rs/imageproc/pull/329

**Comment by HeroicKatora** [comment]
If I see this right, then the pixels are indeed at relative coordinates (6, 8) and have distance exactly (10). Hence floating point error might be the cause of this all. Don't know how pillow avoids it.

**Comment by Aloxaf** [comment]
@theotherphil Wow, that's great. Thank you very much.
But will this lead to some performance loss?
If draw_filled_ellipse_mut is much more slower than draw_filled_circlw_mut, I think just tell the users not to use it when radius is small in document is also a good idea.

**Comment by HeroicKatora** [comment]
@theotherphil Wouldn't it be a better idea to draw the axis-aligned ellipse in horizontal strips rather than drawing a lot of lines from the mid-point outward?

**Comment by theotherphil** [comment]
@HeroicKatora sounds plausible to me. I'm not sure of the rationale behind the current implementation (added in https://github.com/image-rs/imageproc/pull/153).

**Comment by HeroicKatora** [comment]
Retrospect: The difference seems to have been different algorithms. [See the PR diff](https://github.com/image-rs/imageproc/pull/330/files). I'll try to dig a bit into the details. Both algorithms have the same motivation, iterate along one direction until the 45° angle and go one pixel along the perpendicular if we'd leave the circle too much. The pixel is simple painted 4 times for each mirror axis of the circle/aa-conic The difference is as follows:

In the old version:
* `err` tracks the deviation of the 'current pixels distance from the centre' and 'radius'.
* [This condition](https://github.com/image-rs/imageproc/pull/330/files#diff-7d1cd912fe998dcbf78dfcd8bf9ed700L216) checks if going perpendicular would lead to a **smaller absolute** error of deviation.

In the new version:
* `p` tracks the error of the **next** pixel we'd be at if we were to go to the next and then perpendicular.
* [This condition](https://github.com/image-rs/imageproc/pull/330/files#diff-7d1cd912fe998dcbf78dfcd8bf9ed700R215) checks thus if the error is negative, i.e. when we next go perpendicular we would still be within the circle.

It seems that pillow also employs the second algorithm instead of the first, hence the difference. Since it looks better for smaller radius and not very different for large ones this seems to be a fine choice. Still cleaning up the efficiency is a possibility in the future.
