### ISSUE TITLE
getting a Projection by from_control_points makes program freezing

### ISSUE THREAD

**Issue by kingrongH** [image-rs/imageproc#412]
This occurs every time you run the program. Here is the minimal code.
```Rust
fn main() -> Result<(), Box<dyn Error>>{
    println!("get a projection from control points...");
    let from = [(0.0, 0.0), (250.0, 17.481735), (7.257017, 82.94814), (250.0, 104.18543)]; 
    let to = [(0.0, 0.0), (249.0, 0.0), (0.0, 105.0), (249.0, 105.0)];
    let projection = Projection::from_control_points(from, to);
    match projection {
        Some(_p) => println!("new projection"),
        None => println!("failed")
    }
    Ok(())
}
```
Here is all the output I get, nothing else: 
![image](https://user-images.githubusercontent.com/42315902/77247156-51534900-6c69-11ea-863b-ad362976c41b.png)
I think `Projection::from_control_points` should either return Some(_) or None, rather than just keeps freezing. 
Thanks all the work you have done! This may be a bug, please someone check it.

**Comment by theotherphil** [comment]
I see "failed" printed when running in both debug and release modes using the following toolchain:

stable-x86_64-apple-darwin (default)
rustc 1.40.0 (73528e339 2019-12-16)

Which compiler version and architecture are you using?

**Comment by kingrongH** [comment]
sorry I forgot to metion that, my toolchain：

stable-x86_64-unknown-linux-gnu (default)
rustc 1.41.0 (5e1a79984 2020-01-27)

**Comment by kingrongH** [comment]
I just run this demo using 1.40.0, still get freezing. 
I'm using Pop!_OS 19.10

**Comment by Palladinium** [comment]
I can confirm 100% CPU usage and freezing from the example on imageproc `0.20.0`.

Running Arch Linux x84_64, and tested on both debug and release with all of:
- `rustc 1.45.0-nightly (a74d1862d 2020-05-14)`
- `rustc 1.44.0-beta.4 (02c25b359 2020-05-23)`
- `rustc 1.43.1 (8d69840ab 2020-05-04)`

Doing some basic profiling ([flamegraph](https://user-images.githubusercontent.com/3919824/83225696-b07e8e00-a1c3-11ea-91b1-8d307e273f20.png)) points to somewhere inside the `svd()` call, so maybe the issue lies within the `rulinalg`.
This issue in particular seems related: https://github.com/AtheMathmo/rulinalg/issues/176
