### ISSUE TITLE
Operate in f32 and f64 modes

### ISSUE THREAD

**Issue by TianyiShi2001** [image-rs/imageproc#437]
AFAIK the many image processing libraries use doubles. Would it be helpful to make imageproc to operate in both f32 and f64 modes? What would be the best way to achieve this?

**Comment by TianyiShi2001** [comment]
I simple solution I can think of is to:

```
#[cfg(feature = "f32")]
type Float = f32;
#[cfg(feature = "f64")]
type Float = 64
```

Since one usually don't need to use some image operations with `f32` and some others with `f64`

**Comment by HeroicKatora** [comment]
Features in `cargo` are supposed to be (super-)additive. When two downstream crates require `imageproc` then each of them might choose a different set of features but in the cargo build system _all_ of the chosen features are activated. There is currently a thread on [internals proposing a mechanism for exclusive features](https://internals.rust-lang.org/t/pre-rfc-cargo-mutually-exclusive-features/13182/).

**Comment by theotherphil** [comment]
I don't think this is something we can easily support.

**Comment by ripytide** [comment]
The solution to generic floating point and other image operations is not conditional compilation, but rather generic functions with appropriate bounds. The `num` crate is designed precisely for this purpose (and is already used in some places). 

However, due to the sheer number of functions this genericness could be applied to I think it is best for us to have a policy that functions should be made more generic as and when people need them to be by making PRs and such, as to not prematurely complicate function signatures unnecessarily which could make maintenance more tedious.
