### ISSUE TITLE
Maintenance discussion

### ISSUE THREAD

**Issue by bvssvni** [image-rs/imageproc#547]
I was asked to review https://github.com/image-rs/imageproc/pull/541 possibly because I'm listed as the 2nd contributor, but I don't contribute much long to projects under image-rs, due to handing over leadership to the great @fintelia and the great @HeroicKatora.

The reason for this change was a security incidence under the Piston project targeting me specifically and we created this organization to reduce the attack surface. This strategy worked and I have not recorded any further security incidences. I'm just here to help in case there are some special circumstances.

I see several PRs being queued up here. The maintainer, @theotherphil, is not active. As natural in this situation, if @theotherphil does not respond, which can be for many reasons, I recommend that somebody steps up and takes over the maintenance, at least until @theotherphil returns. It is a fairly popular project on crates.io, so I don't think there should be a problem to find motivation to keep this project running.

Maybe @fintelia and @HeroicKatora have some input about how to proceed this discussion? I am just starting this discussion in case people feel this is something that should be discussed, but for maybe reasons they don't feel comfortable being in that role.

**Comment by theotherphil** [comment]
I’ll review recent PRs and issues this weekend. I’m still around and have been meaning to catch up for a while, but haven’t had much energy for library maintenance. I’m happy to hand over maintenance if anyone is interested.

**Comment by bvssvni** [comment]
@theotherphil I'm sorry for the intrusion! It was not my intention to ask you to step down, but now I read my comment this sounds a bit that way. Again, sorry!

I think that as popular this project is, having a co-maintainer is a good idea to lessen your own burden. This is also more fun and might generate more motivation and energy. This way you don't have to think about it and you get more freedom.

Btw, congratulations on 1 million downloads! 🥳 🎉 
You have done an amazing job all these years!

**Comment by theotherphil** [comment]
No worries - I didn’t take it that way!

And wow - that’s a lot more downloads, and a lot more dependent crates, than when I last looked.

**Comment by HeroicKatora** [comment]
Since I'm in a similar spot, having run behind on reviews and overall since about a year, I'll say that having @fintelia as the second maintainer definitely worked out positively. It's made iniatives and asking for help / reviewers possible that wouldn't have been otherwise. Thank you all, a lot.

>  I’m happy to hand over maintenance if anyone is interested.

Like fintelia did for me, how do you feel about posting an 'Asking for …' thread? It doesn't need to mean you stepping down from any over responsibilities.

That said, I'm no friend of simple platitudes. Asking for help is not easy and some of the kind that arrives early will paradoxically take additional effort to filter and cultivate. That's not the mountain to climb when you're already (on the brink of being) burnt out over it, for instance (*wink*, *nudge*, self-reflection). (At least to that extent, I'm not convinced of the usefulness of RustSec tracking implicitly unmaintained crates). Users don't see any of this until the advisory.

**Comment by theotherphil** [comment]
I’m going to close this thread as I’m back to spending a bit of time each week keeping up with PRs and issues.

@ripytide contributions are definitely welcome though!
