### ISSUE TITLE
Remove top-level clippy allows

### ISSUE THREAD

**Issue by ripytide** [image-rs/imageproc#616]
As discussed in https://github.com/image-rs/imageproc/pull/598#discussion_r1595832308 it might be a good idea to remove the top-level clippy allows and instead fix or allow lints on a case-by-case basis.

**Comment by theotherphil** [comment]
@ripytide most of these turned out to be totally unnecessary and a few more were easy to address.

Just two left now:
* zero_prefixed_literal: quite a few uses left; I'd be fine standardising on not using 0 prefixes
* needless_range_loop: also quite a few uses left; I had a quick glance and the suggestions didn't obviously look to me improvements. I'd be happy to take a look at a PR that implements these suggestions but there's a risk I'd reject it

**Comment by theotherphil** [comment]
Actually, I'll do the zero_prefixed_literals one.

**Comment by ripytide** [comment]
`needless_range_loop` indeed seems contentious for this very array-based library. I think this issue is worth closing then.
